### ISSUE TITLE
TypeError: Cannot read property 'forEach' of null when attempting to getRegistrations

### ISSUE THREAD

**Issue by pjohnmeyer** [RusticiSoftware/scormcloud-api-v2-client-javascript#1]
**Steps to reproduce**
In a Node environment with the 1.0.0-beta package installed, the following code will trigger the error:

```js
var RusticiSoftwareCloudV2 = require("@rusticisoftware/scormcloud-api-v2-client-javascript");

var defaultClient = RusticiSoftwareCloudV2.ApiClient.instance
var APP_NORMAL = defaultClient.authentications['APP_NORMAL']
APP_NORMAL.username = // YOUR APP ID
APP_NORMAL.password = // YOUR APP SECRET KEY

var api = new RusticiSoftwareCloudV2.RegistrationApi
api.getRegistrations({'learnerId': 'test@example.com'}, (e,d,r) => { 
  console.log(r.body)
})
```
**Expected result**
Response body `r.body` would be logged to the console

**Actual result**
```
TypeError: Cannot read property 'forEach' of null
    at exports.applyAuthToRequest (/app/node_modules/@rusticisoftware/scormcloud-api-v2-client-javascript/src/rustici-software-cloud-v2/ApiClient.js:278:15)
    at exports.callApi (/app/node_modules/@rusticisoftware/scormcloud-api-v2-client-javascript/src/rustici-software-cloud-v2/ApiClient.js:369:10)
    at exports.getRegistrations (/app/node_modules/@rusticisoftware/scormcloud-api-v2-client-javascript/src/rustici-software-cloud-v2/rustici-software-cloud-v2-api/RegistrationApi.js:1112:29)
```

**Investigative Notes**
I noticed that there are two versions of `ApiClient.js` in the library; for one of them, `authNames` is the 8th parameter, and one of them is the 9th parameter. It appears that the wrong one is being called. When I copy the version at `src/ApiClient.js` over the version at `src/rustici-software-cloud-v2/ApiClient.js`, the problem goes away.

**Comment by DillGromble** [comment]
This issue should be fixed by #2
